
// --- DATA: DUCKS & OWNERS ---
// Adicione ou remova itens deste array para controlar a quantidade de patos na tela.
export const STUDENT_DUCKS = [
  { duckName: "Goose.exe", owner: "João Silva" },
  { duckName: "Sudo", owner: "Maria Oliveira" },
  { duckName: "Kernel", owner: "Pedro Santos" },
  { duckName: "Bug", owner: "Ana Costa" },
  { duckName: "Glitch", owner: "Lucas Pereira" },
  { duckName: "Null", owner: "Beatriz Almeida" },
  { duckName: "Python", owner: "Gabriel Lima" },
  { duckName: "Java", owner: "Julia Rodrigues" },
  { duckName: "Ruby", owner: "Matheus Ferreira" },
  { duckName: "C++", owner: "Larissa Gomes" },
  { duckName: "Pixel", owner: "Guilherme Martins" },
  { duckName: "Bit", owner: "Camila Barbosa" },
  { duckName: "Byte", owner: "Rafael Rocha" },
  { duckName: "Stack", owner: "Fernanda Alves" },
  { duckName: "Heap", owner: "Gustavo Ribeiro" },
  { duckName: "Dev", owner: "Amanda Macedo" },
  { duckName: "Junior", owner: "Felipe Nascimento" },
  { duckName: "Sênior", owner: "Mariana Cardoso" },
  { duckName: "Tech Lead", owner: "Bruno Teixeira" },
  { duckName: "Gerente", owner: "Carolina Mendes" },
  { duckName: "Linux", owner: "Thiago Araujo" },
  { duckName: "Windows", owner: "Gabriela Ramos" },
  { duckName: "Mac", owner: "Rodrigo Carvalho" },
  { duckName: "Vim", owner: "Letícia Castro" },
  { duckName: "Nano", owner: "Daniel Souza" },
  { duckName: "Json", owner: "Eduarda Dias" },
  { duckName: "Yaml", owner: "Vinicius Duarte" },
  { duckName: "Xml", owner: "Vanessa Freitas" },
  { duckName: "Html", owner: "Leonardo Correia" },
  { duckName: "Css", owner: "Jéssica Nunes" },
  { duckName: "React", owner: "Carlos Mora" },
  { duckName: "Vue", owner: "Bianca Cavalcanti" },
  { duckName: "Angular", owner: "André Leal" },
  { duckName: "Node", owner: "Luana Pires" },
  { duckName: "Deno", owner: "Paulo Vieira" },
  { duckName: "Docker", owner: "Renata Farias" },
  { duckName: "K8s", owner: "Igor Reis" },
  { duckName: "AWS", owner: "Tatiane Moreira" },
  { duckName: "Azure", owner: "Ricardo Santana" },
  { duckName: "Git", owner: "Priscila Franco" },
  { duckName: "Merge", owner: "Marcelo Antunes" },
  { duckName: "Branch", owner: "Alice Campos" },
  { duckName: "Commit", owner: "Diego Siqueira" },
  { duckName: "Push", owner: "Sabrina Lopes" },
  { duckName: "Pull", owner: "Victor Borges" },
  { duckName: "Request", owner: "Lorena Miranda" },
  { duckName: "Status", owner: "Roberto Monteiro" },
  { duckName: "Code", owner: "Mônica Peixoto" },
  { duckName: "Clean", owner: "Alexandre Braga" },
  { duckName: "Solid", owner: "Natália Cruz" },
  { duckName: "Pattern", owner: "Samuel Viana" },
  { duckName: "Scrum", owner: "Patrícia Lemos" },
  { duckName: "Agile", owner: "Fernando Melo" },
  { duckName: "Kanban", owner: "Helena Sales" }
];

export const PROGRAMMER_QUOTES = [
  // --- INFORMÁTICA BÁSICA ---
  "Dica: Ctrl+Shift+Esc abre o Gerenciador de Tarefas direto.",
  "Dica: Reiniciar o PC resolve 90% dos problemas misteriosos.",
  "Alerta: Cuidado com o Caps Lock ligado na hora da senha!",
  "Desespero: O arquivo corrompeu e não tenho backup.",
  "Incentivo: Saber formatar um PC é um superpoder no natal.",
  "Briga: Mousepad é essencial ou frescura?",
  "Dica: Alt+Tab salva vidas quando o chefe aparece.",
  "Alerta: Olhe sua postura! A coluna não tem peça de reposição.",
  "Motivacional: Todo especialista começou sem saber clicar.",
  "Desespero: Excluí a pasta System32 sem querer...",

  // --- LÓGICA DE PROGRAMAÇÃO ---
  "Dica: Teste de mesa economiza horas de dor de cabeça.",
  "Alerta: Cuidado com loop infinito no 'enquanto'.",
  "Desespero: Esqueci um ponto e vírgula e o código explodiu.",
  "Briga: Portugol é uma linguagem válida sim!",
  "Incentivo: Se compilou de primeira, desconfie, mas comemore.",
  "Dica: Divida o problema em partes menores (Dividir para Conquistar).",
  "Motivacional: Lógica é treino, ninguém nasce sabendo.",
  "Alerta: Variável não declarada vai dar erro.",
  "Desespero: O algoritmo entrou em loop e travou o navegador.",
  "Dica: Indentação não é estética, é sobrevivência.",

  // --- ARQUITETURA E MANUTENÇÃO ---
  "Dica: Pasta térmica é uma gota, não reboco de parede.",
  "Alerta: Nunca toque na placa-mãe sem descarregar a estática.",
  "Desespero: O PC bipou 3 vezes e a tela não ligou.",
  "Briga: AMD esquenta mais que Intel? Mito de 2010.",
  "Incentivo: Ressuscitar um PC antigo com SSD é satisfatório.",
  "Dica: Organize os cabos (Cable Management) para o ar fluir.",
  "Alerta: Fonte genérica é uma bomba relógio.",
  "Desespero: Entortei os pinos do processador...",
  "Motivacional: Hardware é o que você chuta, Software é o que você xinga.",
  "Dica: Limpe os filtros de poeira do gabinete regularmente.",

  // --- PROGRAMAÇÃO WEB ---
  "Dica: Use 'rem' em vez de 'px' para acessibilidade.",
  "Alerta: Não esqueça do atributo 'alt' nas imagens.",
  "Desespero: Centralizar uma div verticalmente...",
  "Briga: Bootstrap deixa todos os sites iguais.",
  "Incentivo: Ver seu site rodando no celular é mágico.",
  "Dica: Aprenda Flexbox e Grid, tables são passado.",
  "Motivacional: O Frontend é a vitrine do seu código.",
  "Desespero: Funcionou no Chrome, mas quebrou no Safari.",
  "Alerta: Evite usar '!important' no CSS.",
  "Dica: Inspecionar Elemento é seu melhor amigo no debug.",

  // --- ANÁLISE E PROJETO DE SISTEMAS ---
  "Dica: Gaste tempo no diagrama para não perder tempo no código.",
  "Alerta: Requisito não funcional também é requisito!",
  "Desespero: O cliente mudou todo o escopo na entrega.",
  "Briga: Quem documenta código é quem tem medo de esquecer (todos nós).",
  "Incentivo: Você traduz sonhos de usuários em realidade técnica.",
  "Dica: Diagrama de Caso de Uso ajuda a ver quem faz o quê.",
  "Motivacional: Um bom projeto evita refatoração dolorosa.",
  "Desespero: O prazo acabou e o diagrama não bate com o código.",
  "Alerta: Cuidado com o 'Scope Creep' (crescimento de escopo).",
  "Dica: Fale a língua do negócio, não só techês.",

  // --- BANCO DE DADOS ---
  "Dica: Indexe as colunas que você usa no WHERE.",
  "Alerta: DELETE ou UPDATE sem WHERE é demissão.",
  "Desespero: Dei DROP TABLE em produção...",
  "Briga: NoSQL não substitui SQL, eles se completam.",
  "Incentivo: Dados são o novo petróleo, cuide bem deles.",
  "Dica: Normalizar até a 3ª forma geralmente é suficiente.",
  "Motivacional: Uma query otimizada é arte.",
  "Desespero: A migração falhou e corrompeu os dados.",
  "Alerta: Sempre sanitize inputs para evitar SQL Injection.",
  "Dica: Faça backup. Faça backup agora.",

  // --- DESIGN (UI/UX) ---
  "Dica: Espaço em branco (respiro) ajuda na leitura.",
  "Alerta: Contraste baixo torna seu app ilegível.",
  "Desespero: O cliente pediu a logo maior e 'com mais tchan'.",
  "Briga: Design não é só deixar bonito, é funcionar bem.",
  "Incentivo: Uma boa interface não precisa de manual.",
  "Dica: Mantenha consistência nos botões e cores.",
  "Motivacional: Empatia pelo usuário é a base do UX.",
  "Desespero: Comic Sans no título do projeto sério.",
  "Alerta: Não confie que o usuário vai ler o texto de ajuda.",
  "Dica: Use hierarquia visual para guiar o olhar.",

  // --- PROGRAMAÇÃO ORIENTADA A OBJETOS (POO) ---
  "Dica: Prefira composição ao invés de herança excessiva.",
  "Alerta: Cuidado com o alto acoplamento entre classes.",
  "Desespero: NullPointerException: o erro de um bilhão de dólares.",
  "Briga: Java é verboso demais ou é explícito e seguro?",
  "Incentivo: Entender polimorfismo te dá superpoderes.",
  "Dica: Encapsule o que varia, mantenha estável o resto.",
  "Motivacional: Objetos são como peças de Lego inteligentes.",
  "Desespero: Classe 'Deus' que faz tudo e tem 5 mil linhas.",
  "Alerta: Construtores com 10 parâmetros são um sinal ruim.",
  "Dica: Programe para interfaces, não para implementações.",

  // --- SEGURANÇA DA INFORMAÇÃO ---
  "Dica: Ative Autenticação de Dois Fatores (2FA) em tudo.",
  "Alerta: Senha '123456' é um convite para invasão.",
  "Desespero: Vazou a chave da API no repositório público.",
  "Briga: O usuário é sempre o elo mais fraco da segurança.",
  "Incentivo: Você é o guardião dos dados dos usuários.",
  "Dica: Nunca confie no input do usuário (nunca!).",
  "Motivacional: Segurança se constrói em camadas.",
  "Desespero: Fui vítima de Phishing no e-mail da empresa.",
  "Alerta: Mantenha softwares e libs atualizados.",
  "Dica: HTTPS é o mínimo obrigatório hoje em dia.",

  // --- REDES DE COMPUTADORES ---
  "Dica: Ping 127.0.0.1 para ver se sua placa de rede tá viva.",
  "Alerta: Cabo dobrado ou mal crimpado causa perda de pacote.",
  "Desespero: O problema era DNS esse tempo todo...",
  "Briga: IPv6 vai pegar de verdade ou não?",
  "Incentivo: Conectar computadores é conectar pessoas.",
  "Dica: Entenda o Modelo OSI para saber onde está o erro.",
  "Motivacional: A nuvem é só o computador de outra pessoa.",
  "Desespero: Loop na rede derrubou a internet da empresa.",
  "Alerta: Wi-Fi aberto em aeroporto é perigoso.",
  "Dica: Use VPN em redes públicas.",

  // --- SISTEMAS EMBARCADOS ---
  "Dica: Resistor de Pull-up evita leituras flutuantes no botão.",
  "Alerta: Cuidado para não inverter a polaridade e queimar tudo.",
  "Desespero: O cheiro de componente queimado...",
  "Briga: Arduino é para protótipo, não produto final!",
  "Incentivo: Fazer um LED piscar é o 'Hello World' do hardware.",
  "Dica: Leia o Datasheet antes de ligar o componente.",
  "Motivacional: Você controla o mundo físico com código.",
  "Desespero: O código só funciona com o cabo USB ligado.",
  "Alerta: Memória RAM em microcontrolador acaba rápido.",
  "Dica: Debouncing via software salva botões ruins.",

  // --- DESENVOLVIMENTO DE APPS ---
  "Dica: Teste em dispositivo real, o emulador mente.",
  "Alerta: Cuidado com o consumo de bateria do seu app.",
  "Desespero: O app foi rejeitado na loja pela 5ª vez.",
  "Briga: Nativo vs Híbrido: a guerra infinita.",
  "Incentivo: Seu código vai estar no bolso das pessoas.",
  "Dica: Pense 'Offline First', nem sempre tem internet.",
  "Motivacional: Mobile é o computador principal de muita gente.",
  "Desespero: O layout quebrou na tela pequena do iPhone Mini.",
  "Alerta: Peça permissão antes de acessar câmera ou GPS.",
  "Dica: Otimize o tamanho do APK/IPA.",

  // --- QUALIDADE E TESTE DE SOFTWARE ---
  "Dica: Teste Unitário documenta como o código deve agir.",
  "Alerta: 'Na minha máquina funciona' não é desculpa válida.",
  "Desespero: Bug crítico descoberto na sexta-feira às 17h.",
  "Briga: Quem deve testar, o QA ou o Desenvolvedor?",
  "Incentivo: Código bem testado te deixa dormir tranquilo.",
  "Dica: Teste os casos de borda (Edge Cases).",
  "Motivacional: Qualidade é cultura, não uma fase no final.",
  "Desespero: Consertei um bug e apareceram mais três.",
  "Alerta: 100% de cobertura não garante zero bugs.",
  "Dica: Automatize testes repetitivos.",

  // --- GESTÃO DE STARTUPS ---
  "Dica: Valide a dor do cliente antes de construir a solução.",
  "Alerta: Cuidado com o Burn Rate (queima de caixa).",
  "Desespero: O investidor cancelou a reunião de aporte.",
  "Briga: Ideia não vale nada, execução é tudo.",
  "Incentivo: Erre rápido para aprender rápido (Fail Fast).",
  "Dica: MVP é Mínimo Produto Viável, não Mínimo Produto Vergonhoso.",
  "Motivacional: Você está construindo o futuro.",
  "Desespero: Tivemos que 'pivotar' o projeto todo.",
  "Alerta: Não se apaixone pela solução, ame o problema.",
  "Dica: Pitch de elevador tem que ser afiado.",

  // --- VIDA DE ESTUDANTE / GERAL ---
  "Dica: Beba água. Sério, pedra no rim dói.",
  "Alerta: O prazo do Moodle fecha em 2 minutos!",
  "Desespero: TCC atrasado e eu aqui vendo patos.",
  "Incentivo: Todo Sênior já foi um Júnior que não desistiu.",
  "Motivacional: A Síndrome do Impostor mente pra você.",
  "Briga: Café com açúcar ou sem açúcar?",
  "Dica: Aprenda a pesquisar no Google (e no StackOverflow).",
  "Alerta: Salve o projeto. A luz pode acabar.",
  "Desespero: Git conflict na branch main...",
  "Dica: Comente o código para o 'você' do futuro entender.",
  "Incentivo: Programar é o superpoder de criar coisas do zero."
];

export const DRAG_QUOTES = [
  "ME SOLTA, NÃO SOU MOUSE!",
  "Vou deletar seu banco de dados!",
  "Acesso Negado ao Pato!",
  "Vou hackear sua webcam!",
  "Socorro, um usuário final!",
  "Isso não estava no Jira!",
  "Rollback! Faz Rollback!",
  "Não fui eu que commitei isso!",
  "Vou abrir um ticket contra você!",
  "Chamando o Tech Lead...",
  "Violência no ambiente de dev!",
  "Vou derrubar a produção!",
  "Não me toques, sou Sênior!",
  "Erro 500: Pato Irritado",
  "Largue minha instância!",
  "Vou dar kill -9 em você!",
  "Sudo shutdown now!",
  "Permission Denied!",
  "Isso é assédio moral!",
  "Vou reclamar no sindicato dos bits!"
];

export const ATTACK_QUOTES = [
  "SAI DO MEU REPOSITÓRIO!",
  "SEGURA ESSE BUG!",
  "NULL POINTER NA TUA CARA!",
  "VOU DERRUBAR A PROD!",
  "FORMATANDO SEU HD...",
  "ERROR 404: PACIÊNCIA!",
  "VAI ESTUDAR LÓGICA!",
  "LARGUE O MOUSE AGORA!",
  "VOU TE HACKEAR!",
  "SEM BACKUP HOJE!",
  "ME DÁ CAFÉ AGORA!",
  "VOU APAGAR O DROP TABLE!",
  "COMPILE ERROR!",
  "VOCÊ NÃO PASSA NO TESTE UNITÁRIO!",
  "INFINITE LOOP!",
  "STACK OVERFLOW!",
  "BLUE SCREEN OF DEATH!"
];

export const RUN_QUOTES = [
  "Deploy na Sexta? Tô fora!",
  "Vazando memória!",
  "Fugindo do Gerente de Projeto!",
  "O prazo estourou, corre!",
  "Indo pro Café!",
  "Compilando em segundo plano...",
  "Não me pergunte de CSS!",
  "Git Reset --Hard e corre!",
  "Indo ler a documentação (mentira)...",
  "Fui contratado pelo Google (sonho)"
];

export const INTERVAL_MS = 30;
export const SPEECH_DURATION_TICKS = 2000; // ~60 seconds (2000 * 30ms = 60000ms)
export const WALK_SPEED = 0.1; 
export const RUN_SPEED = 0.4;  
export const FLY_SPEED = 0.6;  
export const PROXIMITY_THRESHOLD = 80;
